name = "ACRE Arsenal Tab"
author = "Andx"
prefix = "aat"
mainprefix = "z"

[version]
git_hash = 0

[hemtt.publish]
description = "workshop/steam_description.md"
changelog = "CHANGELOG.md"

[files]
include = [
    "LICENSE",
    "/img/*.paa",
    "/img/*.png",
    "*.bikey",
]
